### PR TITLE
Refactor FontEngine, InputState, SoundManager. Separate SDL dependent code

### PR DESCRIPTION
**Pull request by igorko**
This will allow to use different API for text rendering instead of SDL. Can we merge this? If there is no denial, I will improve abstraction level by moving more API independant code to base class.

### CODE REVIEW

**Comment by igorko** [comment]
Can someone look to Linux build? It's some problem in RenderDeviceList. On windows adding forward declaration fixed build but it is strange because include is present too. And it was problem with FontEngine, not SdlFontEngine

**Comment by dorkster** [comment]
@igorko You need to add in CMakeLists.txt:

- SDLFontEngine.cpp to the FLARE_SOURCES variable
- SDLFontEngine.h to the FLARE_HEADERS variable

I have no real objections to this change otherwise.

**Comment by igorko** [comment]
Heh, I have added files manually in msvc project, lol.

**Comment by igorko** [comment]
Do not merge this yet. I will improve code more.

**Comment by igorko** [comment]
@dorkster Feel free to improve code if have any ideas.

**Comment by igorko** [comment]
I will add today later refactored code for InputState and SoundManager. I would like someone to review changes and improve if there is any ideas.

**Comment by igorko** [comment]
Please review!!!

**Comment by dorkster** [comment]
I manually merged this in and added a few fixes for some compiler warnings.

**Pull request closed without merging**
