### PR TITLE
Display music_filename in error log

### PR DESCRIPTION
**Pull request by ludoza**
Makes debugging that sound problems just a little bit easier.

### CODE REVIEW

**Comment by igorko** [comment]
Maybe it would be better to save all that filename into temporary local variable and reuse it, as locate() function can be time consuming, so calling it only once shoul be better.

**Comment by ludoza** [comment]
Now if only there was such a local variable...

Fixed.

**Comment by igorko** [comment]
Well, I meant another thing.
Like this

		if (music_filename != "") {
                         std::string file_path = mods->locate(music_filename);
 		    	music = Mix_LoadMUS(file_path.c_str());
 			if (!music)
                           logError("GameSwitcher: Mix_LoadMUS(%s): %s", file_path.c_str(), Mix_GetError());
              }

So result of locate() call (full path) is saved locally, and error showas full path too

**Comment by igorko** [comment]
This is really minor optimization, and in this case doesn't change anything much, but in some cases calling function few times or more, instead of one call and caching result, can cause huge performance drop.

**Comment by ludoza** [comment]
Done

**Pull request merged**
