### PR TITLE
Cleaned up the docs a bit

### PR DESCRIPTION
**Pull request by ludoza**
README.md was clobbered, so I took the chance to rename it to README.md and clean it up a bit. I fixed the INSTALL.engine ext to INSTALL.md to render the markdown correctly on github.

### CODE REVIEW

**Comment by dorkster** [comment]
The reason for the .engine extension is that we package flare-engine and flare-game into a single archive when distributing on systems that wouldn't normally separate the two. Basically, non-Linux systems.

Both repos contain a README.md as a symlink. Here, it points to README.engine. In flare-game, it points to README. When we create the combined package, I believe we include the flare-game symlink. The important thing is that *both* README.engine and README are included in that archive.

So I ask that you keep the name for README.engine. And instead of renaming INSTALL.engine, create a similar symlink named INSTALL.md that points to INSTALL.engine.

**Comment by ludoza** [comment]
Can we keep the *.md suffix?

I would also like to shuffle the install file around, because it is really easy to install and I feel it is not clear, for example:

## Dependancies

### Debian based systems

Installing dependencies on debian based systems (debian, Ubuntu, Kubuntu, etc):

````sh
    sudo apt-get install libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
    # for development you'll also need:
    sudo apt-get install cmake make g++ git
```

There is also a flare build in the Ubuntu (universe), which actually is [flare-game].

[flare-game]: http://packages.ubuntu.com/source/precise/flare

### OS X

To build Flare you need the [2.0 Development Libraries for SDL][libsdl]: SDL_image, SDL_mixer, and SDL_ttf, with the equivalent 2.0 Runtime Libraries to run the game; or you can use [Homebrew].

```sh
    brew install cmake libvorbis sdl2 sdl2_image sdl2_mixer sdl2_ttf # install the dependancies 
```
[libsdl]: http://www.libsdl.org/download-2.0.php

## Fetch, build and play 

```sh
    git clone https://github.com/clintbellanger/flare-engine.git # clone the latest source code
    git clone https://github.com/clintbellanger/flare-game.git #and game data
    # remember your dependancies
    cd flare-engine
    cmake .
    make # build the executable
    cd ../flare-game 
    ln -s ../flare-game/flare # symlink the executable 
    ./flare # flame on!
```
[Homebrew]: http://brew.sh/

**Comment by dorkster** [comment]
>Can we keep the *.md suffix?

Sure. That's a good idea.

I'd be fine with those changes to the install docs. However, the "fetch, build, play" method is needs to specify linking the default mod. So it should look like this:

```
    git clone https://github.com/clintbellanger/flare-engine.git # clone the latest source code
    git clone https://github.com/clintbellanger/flare-game.git #and game data
    # remember your dependancies
    cd flare-engine
    cmake .
    make # build the executable
    cd ../flare-game/mods
    ln -s ../../flare-engine/mods/default # symlink the default mod
    cd ../
    ln -s ../flare-engine/flare # symlink the executable 
    ./flare # flame on!
```

**Comment by ludoza** [comment]
Please review.

Under the install flare step, to change the path it states:

```
cmake -DCMAKE_INSTALL_PREFIX:STRING="/usr" ..
```

should it not be, with a single dot:

```
cmake -DCMAKE_INSTALL_PREFIX:STRING="/usr" .
```

**Comment by ludoza** [comment]
Fix for the table did not work :( but I'm leaving it as is.

**Comment by dorkster** [comment]
>should it not be, with a single dot

Yes. We used to instruct people to create a build directory and run cmake from there.

**Pull request merged**
